import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="p-1 sm:p-4 md:p-8 h-screen">
      <body className="h-full flex flex-col ">
        <Header />
        <div className="border-4 border-t-0 border-black rounded-3xl rounded-t-none overflow-auto h-auto grow-[1] shrink-[1] basis-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
