import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="p-1 sm:p-4 md:p-8 h-screen">
      <body className="border-4 border-black rounded-3xl overflow-y-scroll">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
